### ISSUE TITLE
Feature: add policy violations in findings for the project

### ISSUE THREAD

**Issue by sahibamittal** [pmckeown/dependency-track-maven-plugin#296]
Currently, we can fetch list of vulnerabilities in a project using this plugin. 
It should also be able to list all policy violations under that project along with vulnerabilities.

Additionally, those policy violations can be used for multiple purposes, say fail the build if there is any particular violation etc.

**Comment by sahibamittal** [comment]
<img width="1416" alt="Screenshot 2022-07-26 at 2 26 00 p m" src="https://user-images.githubusercontent.com/5709882/181021085-1ae5587f-c66c-445c-b7e3-0ec4a4ed8c61.png">

**Comment by pmckeown** [comment]
@sahibamittal - I've created a PR within this project based on your initial coding up of the policy goal.  Please take some time to review it, though bear in mind I have modified it slightly.

https://github.com/pmckeown/dependency-track-maven-plugin/pull/302

Significant changes:
* Renaming the goal from `policies` to `policy-violations` as that is the API that is being used on the server.   Policies are a distinct concept in Dep Track and I din't want to indicate that this goal integrated with the Policy API.
* I removed the thresholds mechanism that you had copied from the `findings` goal.  I didn't quite understand the intent of this config given that the Policy violations already had a violation state that was (I felt) more suited to use here.  So that when the goal is run against a project, if any policies are breached that have a Violation State of FAIL, the the goal will fail.  If the Violation State is WARN, the goal can optionally fail.  If the Violation State is INFO, the goal will succeed.  **This is the bit I would most like your feedback on**.  Are you able to test this change against your workflow and let me know if it meets your use case?  I feel this approach is more in keeping with the intent of the Policy Compliance feature in Dep Track so I would love to test that it meets your use case. 
* Some refactoring of the report generation.
* Additional automation tests for the Mojo.

Outstanding changes:
* I've not created an XSL Stylesheet for HTML Report printing as its fiddly and I want to make sure the slight direction change is the right one first.

**Comment by pmckeown** [comment]
@sahibamittal - have you had any time to review the above PR?  Would be good to get your feedback on it :)

**Comment by sahibamittal** [comment]
Hi @pmckeown  - yes I've reviewed the changes - looks good to me!

**Comment by pmckeown** [comment]
Implemented in #302 

Released in version [1.2.0](https://github.com/pmckeown/dependency-track-maven-plugin/releases/tag/1.2.0)

**Comment by pmckeown** [comment]
@sahibamittal - v1.2.0 has the new goal.  Thanks for your contribution :)
