### ISSUE TITLE
waitUntilBomProcessingComplete=false seems not working as documented

### ISSUE THREAD

**Issue by lguoyu** [pmckeown/dependency-track-maven-plugin#299]
The cmd I was trying is
`mvn io.github.pmckeown:dependency-track-maven-plugin:upload-bom -Ddependency-track.waitUntilBomProcessingComplete=false -Ddependency-track.projectName=test -Ddependency-track.dependencyTrackBaseUrl=http://localhost:8080 -Ddependency-track.apiKey=test -Ddependency-track.projectVersion=latest`

The logging showed it's still waiting for processing 
`
[INFO] --- dependency-track-maven-plugin:1.1.3:upload-bom (default-cli) @ test ---
[INFO] Project Name: test
[INFO] Project Version: latest
[INFO] Plugin is configured to wait for BOM processing to complete
[INFO] BOM uploaded to Dependency Track server
[INFO] Checking for BOM analysis completion
[INFO] Still processing: true
[INFO] Still processing: true
[INFO] Still processing: true
[INFO] Still processing: true
[INFO] Still processing: true
[INFO] Still processing: true
[INFO] Still processing: true
[INFO] Still processing: true
[INFO] Still processing: true
[INFO] Still processing: true
[INFO] Still processing: true
[INFO] Still processing: true
[INFO] Still processing: true
[INFO] Still processing: true
[INFO] Still processing: true
[INFO] Still processing: true
[INFO] Still processing: true
[INFO] Still processing: true
[INFO] Still processing: true
[INFO] Still processing: true
[ERROR] Polling for processing completion was interrupted so continuing: Call 'io.github.pmckeown.dependencytrack.upload.UploadBomAction$$Lambda$53/1678889928@6fd5717c' failed after 20 tries!
`

I looked into the source code and did not found any reference of "waitUntilBomProcessingComplete" property, is there anything I missed?

**Comment by pmckeown** [comment]
Hi, that option was removed a while ago when I refactored the polling logic.  The current documentation on the polling config is up to date.  You will need to supply the desired options in your pom. 

```xml
<configuration>
    <pollingConfig>
        <enabled>true</enabled>
        <pause>500</pause>
        <attempts>40</attempts>
        <timeUnit>MILLIS</timeUnit>
    </pollingConfig>
</configuration>
```

Unless you are also using an old version of dependency track, i think you need to update to use the port 8081.  Dependency Track was split into a Front End and an API Server a few version back and the default ports for these components is 8080 and 8081 respectively.  This might be why you integration is failing.  

Closing this as not an issue.

**Comment by lguoyu** [comment]
@pmckeown thanks for the quick reply, is there a way to configure it via cmd line property, we have lots of project and it's not possible to update all project poms, a cmd line property override will be really helpful.

**Comment by pmckeown** [comment]
> @pmckeown thanks for the quick reply, is there a way to configure it via cmd line property, we have lots of project and it's not possible to update all project poms, a cmd line property override will be really helpful.

Not that I am aware of due to the fact that Maven doesn't support setting nested properties via the CLI.  Unfortunately I was not aware of that limitation of Maven when I created the configuration options for this and the findings failure thresholds.

So `-Ddependency-track.pollingConfig.enabled=false` is not possible. 

I've re-opened this ticket as you are right, the polling config on the main readme is wrong and needs to be updated.  Of course the full solution is the make these options settable vie the CLI...

**Comment by pmckeown** [comment]
Turns out there is a way to set these properties but not without modifying your POM files.  This might not be what you are after but is all I have time to do as making this possible without a big refactor is not possible.  

The documentation will now show how to set these nested polling properties using `-D` command line options IF you set up your usage of the plugin to allow for it in your POM files.
