### ISSUE TITLE
Update to use Java 14

### ISSUE THREAD

**Issue by pmckeown** [pmckeown/dependency-track-maven-plugin#78]
Java 8 is deprecated and tools like Sonar are stopping support for it.  Investigate upgrading to the latest LTS release of Java and do so if everything works as expected.

**Comment by msymons** [comment]
I do not think that the Sonar comment here is correct.  SonarCloud is migrating to a requirement for Java 11+ for the scanner environment starting from October 2020.  I would expect to see SonarQube do this in v8.5, not yet released at time of writing.  None of this prevents building a project for (say) Java 8.  It's only the sonar **analysis** which is affected. 

As an aside, SonarCloud has only been able to scan Java 14 code since July..  and SonarQube still does not support Java 14 (not until 8.5 release).

**Comment by pmckeown** [comment]
Thanks Mark!  Good to know about the only recent support for Java 14 with Sonar.  I might then stick with upgrading to Java 11 for the code scanning as a first step.

**Comment by pmckeown** [comment]
Ah -so this isn't required.  The reason I saw the deprecation warning was due to running the scanner locally.  The Travis builder is already using Java 11 to run the scan and so the scan warning has gone.

Thanks for the comment to make me too into this a bit more!  

Closing this.
